name: miEPG

on:
  schedule:
    - cron: '30 11 * * * ' # Ejecutar a las 13:30 AM
  workflow_dispatch:
permissions:
   contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Instalar xmllint
      run: |
        sudo apt-get update
        sudo apt-get install -y libxml2-utils  # Instalamos xmllint

    - name: Verificar instalación de xmllint
      run: |
        xmllint --version  # Verifica que xmllint esté instalado correctamente

    - name: Dar permisos de ejecución al script
      run: |
        chmod +x .github/workflows/EPG_script.sh

    - name: Ejecutar script
      run: .github/workflows/EPG_script.sh

    - name: Configurar identidad de Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        
    - name: Subir archivos 
      run: |
        git add .
        git commit -m "Nuevo miEPG.xml"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
